Alexina = [
["Leather Long Bow","Red-White"],
["Glow-in-the-Dark robe","*"],
["Cowboy Hat","*"],
["Flute","Blue"],
["Grace Shawl Dress","*"],
["Broadsword","purple"],
["Eyepatch","*"],
["Large Ribbon","*"],
["Odd Round Shield","*"],
["Peculiar Round Shield","*"],
["Principle's Pirate Graceful Plate Armor","*"],
["Victorious Pirate Lorica Segmentata ","*"],
["Blue L-Rod","*"],
["Ice Blue Flute","*"],
["Purple Fluted Short Sword","*"],
["White Crossbow",""],
["Red Face/White Frame Kite Shield","*"],
["Red Flashing Mandolin","*"],
["Red Leather Long Bow","*"],
["Black Face Red Trim Hetero Kite Shield","*"],
["White Face Blue Trim Hetero Kite Shield ","*"],
["Bastard Sword",""],
["Crossbow",""],
["Fluted Short Sword",""],
["Hooked Cutlass",""],
["Ice Wand",""],
["Leather Long Bow",""],
["Lightning Wand",""],
["Long Bow",""],
["Longsword",""],
["Mace",""],
["Warhammer",""],
["Bipennis",""],
["L-Rod",""],
["Sickle",""],
["Flute",""],
["Mandolin",""],
["Music Bottle","A"],
["Music Bottle","B"],
["Music Bottle","C"],
["Music Bottle","D"],
["Music Bottle","E"],
["Music Bottle","F"],
["Music Bottle","G"],
["Beholder's Shield",""],
["Kite Shield",""],
["Round Shield",""],
["Adventurer's Suit",""],
["Big Panache Head Protector",""],
["Big Pelican Protector",""],
["Counter Gauntlet",""],
["Fluted Gauntlet",""],
["Full Leather Armor Set",""],
["Glow-in-the-Dark Muffler Robe",""],
["Grace Shawl Dress",""],
["Graceful Plate Armor",""],
["Leminia's Holy Moon Armor","F"],
["Leminia's Holy Moon Armor","M"],
["Light Melka Chain Mail",""],
["Lorica Segmentata",""],
["Plate Boots",""],
["Round Pauldron Chainmail",""],
["Round Polean Plate Boots",""],
["Striped Kitty Hat",""],
["Wing Half Helm",""],
["Glowing Pot-Belly Spider Statue",""],
["Glowing Stone Bison Statue",""],
["Glowing Stone Gargoyle Statue ",""],
["Glowing Stone Hound Statue",""],
["Pot-belly Spider's Glowing Venom Sac",""],
["Stone Bison's Glowing Horn",""],
["Stone Bison's Tail",""],
["Stone Gargoyle's Glowing Boot",""],
["Stone Gargoyle's Glowing Glove",""],
["Stone Gargoyle's Pauldron",""],
["Stone Hound's Glowing Claws",""],
["Stone Hound's Glowing Tooth",""],
["Stone Imp's Ear",""],
["Stone Imp's Glowing Hat",""],
["Stone Imp's Glowing Jewel",""],
["Stone Imp's Hat",""],
["Stone Imp's Jewel",""],
["Stone Imp's Sandals"],
["Stone Zombie's Bracelet",""],
["Stone Zombie's Eye",""],
["Stone Zombie's Glowing Bracelet",""],
["Stone Zombie's Glowing Headband",""],
["Rank F Prairie's",""],
["Rank D Ostrich ",""],
["Rank C Puddle's ",""],
["Rank B Lizard ",""],
["Rank B Plateau's",""],
["Rank A Metal Needle",""],
["Rank 9 Strange",""],
["Rank 8 Snowfall",""],
["Rank F Staying",""],
["Rank E Forest",""],
["Rank A Difficult",""],
["Rank 9 Damaging",""],
["Rank 8 Inconvenient",""],
["Rank 8 Uncomfortable",""],
["HP & Stamina 50 Potion","x3"],
["HP 50 Potion","x5"],
["HP 100 Potion","x3"],
["Stamina 50 Potion","5"],
["Nao's Explorer Suit",""],
["Age Potion - 10-Year-Old",""],
["Age Potion - 11-Year-Old",""],
["Age Potion - 14-Year-Old",""],
["Age Potion - 15-Year-Old",""],
["Age Potion - 16-Year-Old",""],
["Age Potion - 17-Year-Old",""],
["Dungeon Wax Wing",""],
["Full Recovery Potion","x3"],
["Bastard Sword",""],
["Crossbow",""],
["Fluted Short Sword",""],
["Hooked Cutlass",""],
["Ice Wand",""],
["Leather Long Bow",""],
["Lightning Wand",""],
["Long Bow",""],
["Longsword",""],
["Mace",""],
["Warhammer",""],
["Bipennis",""],
["L-Rod",""],
["Sickle",""],
["Flute",""],
["Mandolin",""],
["Music Bottle","A"],
["Music Bottle","B"],
["Music Bottle","C"],
["Music Bottle","D"],
["Music Bottle","E"],
["Music Bottle","F"],
["Music Bottle","G"],
["Beholder's Shield",""],
["Kite Shield",""],
["Round Shield",""],
["Adventurer's Suit",""],
["Big Panache Head Protector",""],
["Big Pelican Protector",""],
["Counter Gauntlet",""],
["Fluted Gauntlet",""],
["Full Leather Armor Set",""],
["Glow-in-the-Dark Muffler Robe",""],
["Grace Shawl Dress",""],
["Graceful Plate Armor",""],
["Leminia's Holy Moon Armor","F"],
["Leminia's Holy Moon Armor","M"],
["Light Melka Chain Mail",""],
["Lorica Segmentata",""],
["Plate Boots",""],
["Round Pauldron Chainmail",""],
["Round Polean Plate Boots",""],
["Striped Kitty Hat",""],
["Wing Half Helm",""],
["Glowing Pot-Belly Spider Statue",""],
["Glowing Stone Bison Statue",""],
["Glowing Stone Gargoyle Statue ",""],
["Glowing Stone Hound Statue",""],
["Pot-belly Spider's Glowing Venom Sac",""],
["Stone Bison's Glowing Horn",""],
["Stone Bison's Tail",""],
["Stone Gargoyle's Glowing Boot",""],
["Stone Gargoyle's Glowing Glove",""],
["Stone Gargoyle's Pauldron",""],
["Stone Hound's Glowing Claws",""],
["Stone Hound's Glowing Tooth",""],
["Stone Imp's Ear",""],
["Stone Imp's Glowing Hat",""],
["Stone Imp's Glowing Jewel",""],
["Stone Imp's Hat",""],
["Stone Imp's Jewel",""],
["Stone Imp's Sandals"],
["Stone Zombie's Bracelet",""],
["Stone Zombie's Eye",""],
["Stone Zombie's Glowing Bracelet",""],
["Stone Zombie's Glowing Headband",""],
["Rank F Prairie's",""],
["Rank D Ostrich ",""],
["Rank C Puddle's ",""],
["Rank B Lizard ",""],
["Rank B Plateau's",""],
["Rank A Metal Needle",""],
["Rank 9 Strange",""],
["Rank 8 Snowfall",""],
["Rank F Staying",""],
["Rank E Forest",""],
["Rank A Difficult",""],
["Rank 9 Damaging",""],
["Rank 8 Inconvenient",""],
["Rank 8 Uncomfortable",""],
["HP & Stamina 50 Potion","x3"],
["HP 50 Potion","x5"],
["HP 100 Potion","x3"],
["Stamina 50 Potion","5"],
["Nao's Explorer Suit",""],
["Age Potion - 10-Year-Old",""],
["Age Potion - 11-Year-Old",""],
["Age Potion - 14-Year-Old",""],
["Age Potion - 15-Year-Old",""],
["Age Potion - 16-Year-Old",""],
["Age Potion - 17-Year-Old",""],
["Dungeon Wax Wing",""],
["Full Recovery Potion","x3"],
["Bastard Sword",""],
["Crossbow",""],
["Fluted Short Sword",""],
["Hooked Cutlass",""],
["Ice Wand",""],
["Leather Long Bow",""],
["Lightning Wand",""],
["Long Bow",""],
["Longsword",""],
["Mace",""],
["Warhammer",""],
["Bipennis",""],
["L-Rod",""],
["Sickle",""],
["Flute",""],
["Mandolin",""],
["Music Bottle","A"],
["Music Bottle","B"],
["Music Bottle","C"],
["Music Bottle","D"],
["Music Bottle","E"],
["Music Bottle","F"],
["Music Bottle","G"],
["Beholder's Shield",""],
["Kite Shield",""],
["Round Shield",""],
["Adventurer's Suit",""],
["Big Panache Head Protector",""],
["Big Pelican Protector",""],
["Counter Gauntlet",""],
["Fluted Gauntlet",""],
["Full Leather Armor Set",""],
["Glow-in-the-Dark Muffler Robe",""],
["Grace Shawl Dress",""],
["Graceful Plate Armor",""],
["Leminia's Holy Moon Armor","F"],
["Leminia's Holy Moon Armor","M"],
["Light Melka Chain Mail",""],
["Lorica Segmentata",""],
["Plate Boots",""],
["Round Pauldron Chainmail",""],
["Round Polean Plate Boots",""],
["Striped Kitty Hat",""],
["Wing Half Helm",""],
["Glowing Pot-Belly Spider Statue",""],
["Glowing Stone Bison Statue",""],
["Glowing Stone Gargoyle Statue ",""],
["Glowing Stone Hound Statue",""],
["Pot-belly Spider's Glowing Venom Sac",""],
["Stone Bison's Glowing Horn",""],
["Stone Bison's Tail",""],
["Stone Gargoyle's Glowing Boot",""],
["Stone Gargoyle's Glowing Glove",""],
["Stone Gargoyle's Pauldron",""],
["Stone Hound's Glowing Claws",""],
["Stone Hound's Glowing Tooth",""],
["Stone Imp's Ear",""],
["Stone Imp's Glowing Hat",""],
["Stone Imp's Glowing Jewel",""],
["Stone Imp's Hat",""],
["Stone Imp's Jewel",""],
["Stone Imp's Sandals"],
["Stone Zombie's Bracelet",""],
["Stone Zombie's Eye",""],
["Stone Zombie's Glowing Bracelet",""],
["Stone Zombie's Glowing Headband",""],
["Rank F Prairie's",""],
["Rank D Ostrich ",""],
["Rank C Puddle's ",""],
["Rank B Lizard ",""],
["Rank B Plateau's",""],
["Rank A Metal Needle",""],
["Rank 9 Strange",""],
["Rank 8 Snowfall",""],
["Rank F Staying",""],
["Rank E Forest",""],
["Rank A Difficult",""],
["Rank 9 Damaging",""],
["Rank 8 Inconvenient",""],
["Rank 8 Uncomfortable",""],
["HP & Stamina 50 Potion","x3"],
["HP 50 Potion","x5"],
["HP 100 Potion","x3"],
["Stamina 50 Potion","5"],
["Nao's Explorer Suit",""],
["Age Potion - 10-Year-Old",""],
["Age Potion - 11-Year-Old",""],
["Age Potion - 14-Year-Old",""],
["Age Potion - 15-Year-Old",""],
["Age Potion - 16-Year-Old",""],
["Age Potion - 17-Year-Old",""],
["Dungeon Wax Wing",""],
["Full Recovery Potion","x3"],
["Bastard Sword",""],
["Crossbow",""],
["Fluted Short Sword",""],
["Hooked Cutlass",""],
["Ice Wand",""],
["Leather Long Bow",""],
["Lightning Wand",""],
["Long Bow",""],
["Longsword",""],
["Mace",""],
["Warhammer",""],
["Bipennis",""],
["L-Rod",""],
["Sickle",""],
["Flute",""],
["Mandolin",""],
["Music Bottle","A"],
["Music Bottle","B"],
["Music Bottle","C"],
["Music Bottle","D"],
["Music Bottle","E"],
["Music Bottle","F"],
["Music Bottle","G"],
["Beholder's Shield",""],
["Kite Shield",""],
["Round Shield",""],
["Adventurer's Suit",""],
["Big Panache Head Protector",""],
["Big Pelican Protector",""],
["Counter Gauntlet",""],
["Fluted Gauntlet",""],
["Full Leather Armor Set",""],
["Glow-in-the-Dark Muffler Robe",""],
["Grace Shawl Dress",""],
["Graceful Plate Armor",""],
["Leminia's Holy Moon Armor","F"],
["Leminia's Holy Moon Armor","M"],
["Light Melka Chain Mail",""],
["Lorica Segmentata",""],
["Plate Boots",""],
["Round Pauldron Chainmail",""],
["Round Polean Plate Boots",""],
["Striped Kitty Hat",""],
["Wing Half Helm",""],
["Glowing Pot-Belly Spider Statue",""],
["Glowing Stone Bison Statue",""],
["Glowing Stone Gargoyle Statue ",""],
["Glowing Stone Hound Statue",""],
["Pot-belly Spider's Glowing Venom Sac",""],
["Stone Bison's Glowing Horn",""],
["Stone Bison's Tail",""],
["Stone Gargoyle's Glowing Boot",""],
["Stone Gargoyle's Glowing Glove",""],
["Stone Gargoyle's Pauldron",""],
["Stone Hound's Glowing Claws",""],
["Stone Hound's Glowing Tooth",""],
["Stone Imp's Ear",""],
["Stone Imp's Glowing Hat",""],
["Stone Imp's Glowing Jewel",""],
["Stone Imp's Hat",""],
["Stone Imp's Jewel",""],
["Stone Imp's Sandals"],
["Stone Zombie's Bracelet",""],
["Stone Zombie's Eye",""],
["Stone Zombie's Glowing Bracelet",""],
["Stone Zombie's Glowing Headband",""],
["Rank F Prairie's",""],
["Rank D Ostrich ",""],
["Rank C Puddle's ",""],
["Rank B Lizard ",""],
["Rank B Plateau's",""],
["Rank A Metal Needle",""],
["Rank 9 Strange",""],
["Rank 8 Snowfall",""],
["Rank F Staying",""],
["Rank E Forest",""],
["Rank A Difficult",""],
["Rank 9 Damaging",""],
["Rank 8 Inconvenient",""],
["Rank 8 Uncomfortable",""],
["HP & Stamina 50 Potion","x3"],
["HP 50 Potion","x5"],
["HP 100 Potion","x3"],
["Stamina 50 Potion","5"],
["Nao's Explorer Suit",""],
["Age Potion - 10-Year-Old",""],
["Age Potion - 11-Year-Old",""],
["Age Potion - 14-Year-Old",""],
["Age Potion - 15-Year-Old",""],
["Age Potion - 16-Year-Old",""],
["Age Potion - 17-Year-Old",""],
["Dungeon Wax Wing",""],
["Full Recovery Potion","x3"],
["Bastard Sword",""],
["Crossbow",""],
["Fluted Short Sword",""],
["Hooked Cutlass",""],
["Ice Wand",""],
["Leather Long Bow",""],
["Lightning Wand",""],
["Long Bow",""],
["Longsword",""],
["Mace",""],
["Warhammer",""],
["Bipennis",""],
["L-Rod",""],
["Sickle",""],
["Flute",""],
["Mandolin",""],
["Music Bottle","A"],
["Music Bottle","B"],
["Music Bottle","C"],
["Music Bottle","D"],
["Music Bottle","E"],
["Music Bottle","F"],
["Music Bottle","G"],
["Beholder's Shield",""],
["Kite Shield",""],
["Round Shield",""],
["Adventurer's Suit",""],
["Big Panache Head Protector",""],
["Big Pelican Protector",""],
["Counter Gauntlet",""],
["Fluted Gauntlet",""],
["Full Leather Armor Set",""],
["Glow-in-the-Dark Muffler Robe",""],
["Grace Shawl Dress",""],
["Graceful Plate Armor",""],
["Leminia's Holy Moon Armor","F"],
["Leminia's Holy Moon Armor","M"],
["Light Melka Chain Mail",""],
["Lorica Segmentata",""],
["Plate Boots",""],
["Round Pauldron Chainmail",""],
["Round Polean Plate Boots",""],
["Striped Kitty Hat",""],
["Wing Half Helm",""],
["Glowing Pot-Belly Spider Statue",""],
["Glowing Stone Bison Statue",""],
["Glowing Stone Gargoyle Statue ",""],
["Glowing Stone Hound Statue",""],
["Pot-belly Spider's Glowing Venom Sac",""],
["Stone Bison's Glowing Horn",""],
["Stone Bison's Tail",""],
["Stone Gargoyle's Glowing Boot",""],
["Stone Gargoyle's Glowing Glove",""],
["Stone Gargoyle's Pauldron",""],
["Stone Hound's Glowing Claws",""],
["Stone Hound's Glowing Tooth",""],
["Stone Imp's Ear",""],
["Stone Imp's Glowing Hat",""],
["Stone Imp's Glowing Jewel",""],
["Stone Imp's Hat",""],
["Stone Imp's Jewel",""],
["Stone Imp's Sandals"],
["Stone Zombie's Bracelet",""],
["Stone Zombie's Eye",""],
["Stone Zombie's Glowing Bracelet",""],
["Stone Zombie's Glowing Headband",""],
["Rank F Prairie's",""],
["Rank D Ostrich ",""],
["Rank C Puddle's ",""],
["Rank B Lizard ",""],
["Rank B Plateau's",""],
["Rank A Metal Needle",""],
["Rank 9 Strange",""],
["Rank 8 Snowfall",""],
["Rank F Staying",""],
["Rank E Forest",""],
["Rank A Difficult",""],
["Rank 9 Damaging",""],
["Rank 8 Inconvenient",""],
["Rank 8 Uncomfortable",""],
["HP & Stamina 50 Potion","x3"],
["HP 50 Potion","x5"],
["HP 100 Potion","x3"],
["Stamina 50 Potion","5"],
["Nao's Explorer Suit",""],
["Age Potion - 10-Year-Old",""],
["Age Potion - 11-Year-Old",""],
["Age Potion - 14-Year-Old",""],
["Age Potion - 15-Year-Old",""],
["Age Potion - 16-Year-Old",""],
["Age Potion - 17-Year-Old",""],
["Dungeon Wax Wing",""],
["Full Recovery Potion","x3"],
["Waxen Wing of Goddess",""]
];