Malcolm = [
["Gloss Sagittarius Ring","*"], 
["Luxury Gemini devCAT Brooch","*"],  
["Black Crossbow","*"],  
["Black Ladle","*"],  
["Blue Gathering Knife","*"],  
["Blue Mace","*"],  
["Green Blade Gathering Axe","*"],  
["Green Two-Handed Sword","*"],  
["Hot Pink Bastard Sword","*"],  
["Hot Pink Sickle","*"],  
["Orange Flashing Wool Collection Pouch","*"],  
["Pink Weeding Hoe","*"],  
["Purple Bipennis","*"],  
["Purple Pickaxe","*"],  
["Red Blacksmith Hammer","*"],  
["Red Cooking Pot","*"],  
["Red Cooking Table","*"],  
["Red Gladius","*"],  
["White Rolling Pin","*"],  
["Yellow Cooking Knife","*"],  
["Yellow Dragon Blade","*"],  
["Bastard Sword",""],  
["Bipennis",""],  
["Bone Marine Sword",""],  
["Crossbow",""],  
["Dragon Blade",""],  
["Gladius",""],  
["Hooked Cutlass",""],  
["Japanese One-handed Sword",""],  
["Longsword",""],  
["Mace",""],  
["Two-Handed Sword",""],  
["Blacksmith Hammer",""],  
["Cooking Knife",""],  
["Cooking Pot",""],  
["Cooking Table",""],  
["Fishing Rod",""],  
["Gathering Axe",""],  
["Gathering Knife",""],  
["Ladle",""],  
["Pickaxe",""],  
["Rolling Pin",""],  
["Sickle",""],  
["Weeding Hoe",""],  
["Weaving Gloves",""],  
["Common Silk Weaving Gloves",""],  
["Fine Fabric Weaving Gloves",""],  
["Fine Silk Weaving Gloves",""],  
["Finest Fabric Weaving Gloves",""],  
["Professional Silk Weaving Gloves",""],  
["Advanced Chef's Hat",""],  
["Apron Dress",""],  
["Apprentice Chef's Hat",""], 
["Arish Ashuvain Armor","F"],
["Arish Ashuvain Armor","M"], 
["Bear Robe",""],  
["Big Chain Full Helm",""],  
["Bone Marine Armor","F"],  
["Coco Rabbit Robe",""], 
["Cores' Cute Ribbon Shoes",""],  
["devCAT Brooch",""],  
["Dustin Silver Knight Armor",""],  
["Elegant Gothic Dress Long Type",""],  
["Elegant Gothic Dress Short Type",""],  
["Elegant Gothic Suit",""],  
["Ella's Vest Skirt",""],  
["European Comp",""],  
["Graceful Plate Armor",""],  
["Kirinusjin's Half-plate Armor","F"], 
["Long Swordsmanship School Uniform","M"], 
["Nathane Snow Mountain Coat",""],  
["One Piece Apron",""],  
["Ring",""], 
["Sasha Robe",""],  
["Short Swordsmanship School Uniform","F"],  
["Siren's Bat Wing Mask",""],  
["Siren's Cat Mask",""],  
["Siren's Glasses",""],  
["Siren's Mask",""],  
["Siren's Small Wing Mask",""],  
["Siren's Wing Mask",""],  
["Tioz Armor (F)","Light Pink"],
["Tork's Chef Uniform","F"], 
["Wing Half Helm",""],  
["Xiao-Lung Juen's Dress Shoes","F"],
["XL Pelican Protector",""],  
["Sewing Patterns",""],  
["Bone Marine Armor","M"], 
["Bone Marine Armor","F"],
["Cores' Healer Dress",""],  
["Cores' Healer Gloves",""],  
["Ella's Vest Skirt",""],  
["Kirin's Winter Angel Gloves",""],  
["Kirin's Winter Angel Cap",""],  
["Kirin's Winter Angel Coat","F"],  
["Kirin's Winter Angel Coat","M"], 
["Long Swordsmanship School Uniform","M"],
["Magic School Uniform","F"],   
["Short Swordsmanship School Uniform","F"],
["Xiao-Lung Juen's Formal Suit","F"],   
["Blacksmith Manuals",""],  
["Cuirassier Helm",""],  
["Dagger",""],  
["Dustin Silver Knight Vambrace",""],  
["Fluted Short Sword",""],  
["Japanese Dagger",""],  
["Japanese One-handed Sword",""], 
["Japanese Twin Sword Sword",""],  
["Pickaxe",""], 
["Round Shield",""],  
["Weeding Hoe",""],  
["HP & Stamina 30 Potion","x5"], 
["Production Materials",""],  
["Common Fabric","x10"], 
["Common Finishing Thread","x10"],
["Common Leather","x10"], 
["Copper Ore","x10"], 
["Fine Finishing Thread","x10"],
["Fine Leather","x10"], 
["Fine Leather Strap","x10"], 
["Fine Fabric","x10"], 
["Finest Fabric","x5"], 
["Finest Finishing Thread","x5"],
["Finest Leather","x5"], 
["Finest Leather Strap","x5"],
["Fog Silk","x10"],  
["Fine Silk","x30"], 
["Gold Ingot","x10"], 
["Iron Ore","x10"], 
["Magical Silver Thread","x5"], 
["Magical Golden Thread","x5"],
["Magical Silver Thread","x10"], 
["Magical Golden Thread","x10"],  
["Mythril Ore","x5"], 
["Silver Ore","x10"],
["Thick Thread Ball","x5"], 
["Thin Thread Ball","x5"], 
["Miscellaneous",""],  
["Holy Water of Lymilark","x3"], 
["Wool Collection Pouch",""],  
["Cash Shop/Advanced Play Items",""],  
["Dye Ampoule",""], 
["Fixed Color Dye Ampoule",""],  
["Red Dye Ampoule",""], 
["Bastard Sword",""],  
["Bipennis",""],  
["Bone Marine Sword",""],  
["Crossbow",""],  
["Dragon Blade",""],  
["Gladius",""],  
["Hooked Cutlass",""],  
["Japanese One-handed Sword",""],  
["Longsword",""],  
["Mace",""],  
["Two-Handed Sword",""],  
["Blacksmith Hammer",""],  
["Cooking Knife",""],  
["Cooking Pot",""],  
["Cooking Table",""],  
["Fishing Rod",""],  
["Gathering Axe",""],  
["Gathering Knife",""],  
["Ladle",""],  
["Pickaxe",""],  
["Rolling Pin",""],  
["Sickle",""],  
["Weeding Hoe",""],  
["Weaving Gloves",""],  
["Common Silk Weaving Gloves",""],  
["Fine Fabric Weaving Gloves",""],  
["Fine Silk Weaving Gloves",""],  
["Finest Fabric Weaving Gloves",""],  
["Professional Silk Weaving Gloves",""],  
["Advanced Chef's Hat",""],  
["Apron Dress",""],  
["Apprentice Chef's Hat",""], 
["Arish Ashuvain Armor","F"],
["Arish Ashuvain Armor","M"], 
["Bear Robe",""],  
["Big Chain Full Helm",""],  
["Bone Marine Armor","F"],  
["Coco Rabbit Robe",""], 
["Cores' Cute Ribbon Shoes",""],  
["devCAT Brooch",""],  
["Dustin Silver Knight Armor",""],  
["Elegant Gothic Dress Long Type",""],  
["Elegant Gothic Dress Short Type",""],  
["Elegant Gothic Suit",""],  
["Ella's Vest Skirt",""],  
["European Comp",""],  
["Graceful Plate Armor",""],  
["Kirinusjin's Half-plate Armor","F"], 
["Long Swordsmanship School Uniform","M"], 
["Nathane Snow Mountain Coat",""],  
["One Piece Apron",""],  
["Ring",""], 
["Sasha Robe",""],  
["Short Swordsmanship School Uniform","F"],  
["Siren's Bat Wing Mask",""],  
["Siren's Cat Mask",""],  
["Siren's Glasses",""],  
["Siren's Mask",""],  
["Siren's Small Wing Mask",""],  
["Siren's Wing Mask",""],  
["Tioz Armor (F)","Light Pink"],
["Tork's Chef Uniform","F"], 
["Wing Half Helm",""],  
["Xiao-Lung Juen's Dress Shoes","F"],
["XL Pelican Protector",""],  
["Sewing Patterns",""],  
["Bone Marine Armor","M"], 
["Bone Marine Armor","F"],
["Cores' Healer Dress",""],  
["Cores' Healer Gloves",""],  
["Ella's Vest Skirt",""],  
["Kirin's Winter Angel Gloves",""],  
["Kirin's Winter Angel Cap",""],  
["Kirin's Winter Angel Coat","F"],  
["Kirin's Winter Angel Coat","M"], 
["Long Swordsmanship School Uniform","M"],
["Magic School Uniform","F"],   
["Short Swordsmanship School Uniform","F"],
["Xiao-Lung Juen's Formal Suit","F"],   
["Blacksmith Manuals",""],  
["Cuirassier Helm",""],  
["Dagger",""],  
["Dustin Silver Knight Vambrace",""],  
["Fluted Short Sword",""],  
["Japanese Dagger",""],  
["Japanese One-handed Sword",""], 
["Japanese Twin Sword Sword",""],  
["Pickaxe",""], 
["Round Shield",""],  
["Weeding Hoe",""],  
["HP & Stamina 30 Potion","x5"], 
["Production Materials",""],  
["Common Fabric","x10"], 
["Common Finishing Thread","x10"],
["Common Leather","x10"], 
["Copper Ore","x10"], 
["Fine Finishing Thread","x10"],
["Fine Leather","x10"], 
["Fine Leather Strap","x10"], 
["Fine Fabric","x10"], 
["Finest Fabric","x5"], 
["Finest Finishing Thread","x5"],
["Finest Leather","x5"], 
["Finest Leather Strap","x5"],
["Fog Silk","x10"],  
["Fine Silk","x30"], 
["Gold Ingot","x10"], 
["Iron Ore","x10"], 
["Magical Silver Thread","x5"], 
["Magical Golden Thread","x5"],
["Magical Silver Thread","x10"], 
["Magical Golden Thread","x10"],  
["Mythril Ore","x5"], 
["Silver Ore","x10"],
["Thick Thread Ball","x5"], 
["Thin Thread Ball","x5"], 
["Miscellaneous",""],  
["Holy Water of Lymilark","x3"], 
["Wool Collection Pouch",""],  
["Cash Shop/Advanced Play Items",""],  
["Dye Ampoule",""], 
["Fixed Color Dye Ampoule",""],  
["Red Dye Ampoule",""], 
["Bastard Sword",""],  
["Bipennis",""],  
["Bone Marine Sword",""],  
["Crossbow",""],  
["Dragon Blade",""],  
["Gladius",""],  
["Hooked Cutlass",""],  
["Japanese One-handed Sword",""],  
["Longsword",""],  
["Mace",""],  
["Two-Handed Sword",""],  
["Blacksmith Hammer",""],  
["Cooking Knife",""],  
["Cooking Pot",""],  
["Cooking Table",""],  
["Fishing Rod",""],  
["Gathering Axe",""],  
["Gathering Knife",""],  
["Ladle",""],  
["Pickaxe",""],  
["Rolling Pin",""],  
["Sickle",""],  
["Weeding Hoe",""],  
["Weaving Gloves",""],  
["Common Silk Weaving Gloves",""],  
["Fine Fabric Weaving Gloves",""],  
["Fine Silk Weaving Gloves",""],  
["Finest Fabric Weaving Gloves",""],  
["Professional Silk Weaving Gloves",""],  
["Advanced Chef's Hat",""],  
["Apron Dress",""],  
["Apprentice Chef's Hat",""], 
["Arish Ashuvain Armor","F"],
["Arish Ashuvain Armor","M"], 
["Bear Robe",""],  
["Big Chain Full Helm",""],  
["Bone Marine Armor","F"],  
["Coco Rabbit Robe",""], 
["Cores' Cute Ribbon Shoes",""],  
["devCAT Brooch",""],  
["Dustin Silver Knight Armor",""],  
["Elegant Gothic Dress Long Type",""],  
["Elegant Gothic Dress Short Type",""],  
["Elegant Gothic Suit",""],  
["Ella's Vest Skirt",""],  
["European Comp",""],  
["Graceful Plate Armor",""],  
["Kirinusjin's Half-plate Armor","F"], 
["Long Swordsmanship School Uniform","M"], 
["Nathane Snow Mountain Coat",""],  
["One Piece Apron",""],  
["Ring",""], 
["Sasha Robe",""],  
["Short Swordsmanship School Uniform","F"],  
["Siren's Bat Wing Mask",""],  
["Siren's Cat Mask",""],  
["Siren's Glasses",""],  
["Siren's Mask",""],  
["Siren's Small Wing Mask",""],  
["Siren's Wing Mask",""],  
["Tioz Armor (F)","Light Pink"],
["Tork's Chef Uniform","F"], 
["Wing Half Helm",""],  
["Xiao-Lung Juen's Dress Shoes","F"],
["XL Pelican Protector",""],  
["Sewing Patterns",""],  
["Bone Marine Armor","M"], 
["Bone Marine Armor","F"],
["Cores' Healer Dress",""],  
["Cores' Healer Gloves",""],  
["Ella's Vest Skirt",""],  
["Kirin's Winter Angel Gloves",""],  
["Kirin's Winter Angel Cap",""],  
["Kirin's Winter Angel Coat","F"],  
["Kirin's Winter Angel Coat","M"], 
["Long Swordsmanship School Uniform","M"],
["Magic School Uniform","F"],   
["Short Swordsmanship School Uniform","F"],
["Xiao-Lung Juen's Formal Suit","F"],   
["Blacksmith Manuals",""],  
["Cuirassier Helm",""],  
["Dagger",""],  
["Dustin Silver Knight Vambrace",""],  
["Fluted Short Sword",""],  
["Japanese Dagger",""],  
["Japanese One-handed Sword",""], 
["Japanese Twin Sword Sword",""],  
["Pickaxe",""], 
["Round Shield",""],  
["Weeding Hoe",""],  
["HP & Stamina 30 Potion","x5"], 
["Production Materials",""],  
["Common Fabric","x10"], 
["Common Finishing Thread","x10"],
["Common Leather","x10"], 
["Copper Ore","x10"], 
["Fine Finishing Thread","x10"],
["Fine Leather","x10"], 
["Fine Leather Strap","x10"], 
["Fine Fabric","x10"], 
["Finest Fabric","x5"], 
["Finest Finishing Thread","x5"],
["Finest Leather","x5"], 
["Finest Leather Strap","x5"],
["Fog Silk","x10"],  
["Fine Silk","x30"], 
["Gold Ingot","x10"], 
["Iron Ore","x10"], 
["Magical Silver Thread","x5"], 
["Magical Golden Thread","x5"],
["Magical Silver Thread","x10"], 
["Magical Golden Thread","x10"],  
["Mythril Ore","x5"], 
["Silver Ore","x10"],
["Thick Thread Ball","x5"], 
["Thin Thread Ball","x5"], 
["Miscellaneous",""],  
["Holy Water of Lymilark","x3"], 
["Wool Collection Pouch",""],  
["Cash Shop/Advanced Play Items",""],  
["Dye Ampoule",""], 
["Fixed Color Dye Ampoule",""],  
["Red Dye Ampoule",""], 
["Bastard Sword",""],  
["Bipennis",""],  
["Bone Marine Sword",""],  
["Crossbow",""],  
["Dragon Blade",""],  
["Gladius",""],  
["Hooked Cutlass",""],  
["Japanese One-handed Sword",""],  
["Longsword",""],  
["Mace",""],  
["Two-Handed Sword",""],  
["Blacksmith Hammer",""],  
["Cooking Knife",""],  
["Cooking Pot",""],  
["Cooking Table",""],  
["Fishing Rod",""],  
["Gathering Axe",""],  
["Gathering Knife",""],  
["Ladle",""],  
["Pickaxe",""],  
["Rolling Pin",""],  
["Sickle",""],  
["Weeding Hoe",""],  
["Weaving Gloves",""],  
["Common Silk Weaving Gloves",""],  
["Fine Fabric Weaving Gloves",""],  
["Fine Silk Weaving Gloves",""],  
["Finest Fabric Weaving Gloves",""],  
["Professional Silk Weaving Gloves",""],  
["Advanced Chef's Hat",""],  
["Apron Dress",""],  
["Apprentice Chef's Hat",""], 
["Arish Ashuvain Armor","F"],
["Arish Ashuvain Armor","M"], 
["Bear Robe",""],  
["Big Chain Full Helm",""],  
["Bone Marine Armor","F"],  
["Coco Rabbit Robe",""], 
["Cores' Cute Ribbon Shoes",""],  
["devCAT Brooch",""],  
["Dustin Silver Knight Armor",""],  
["Elegant Gothic Dress Long Type",""],  
["Elegant Gothic Dress Short Type",""],  
["Elegant Gothic Suit",""],  
["Ella's Vest Skirt",""],  
["European Comp",""],  
["Graceful Plate Armor",""],  
["Kirinusjin's Half-plate Armor","F"], 
["Long Swordsmanship School Uniform","M"], 
["Nathane Snow Mountain Coat",""],  
["One Piece Apron",""],  
["Ring",""], 
["Sasha Robe",""],  
["Short Swordsmanship School Uniform","F"],  
["Siren's Bat Wing Mask",""],  
["Siren's Cat Mask",""],  
["Siren's Glasses",""],  
["Siren's Mask",""],  
["Siren's Small Wing Mask",""],  
["Siren's Wing Mask",""],  
["Tioz Armor (F)","Light Pink"],
["Tork's Chef Uniform","F"], 
["Wing Half Helm",""],  
["Xiao-Lung Juen's Dress Shoes","F"],
["XL Pelican Protector",""],  
["Sewing Patterns",""],  
["Bone Marine Armor","M"], 
["Bone Marine Armor","F"],
["Cores' Healer Dress",""],  
["Cores' Healer Gloves",""],  
["Ella's Vest Skirt",""],  
["Kirin's Winter Angel Gloves",""],  
["Kirin's Winter Angel Cap",""],  
["Kirin's Winter Angel Coat","F"],  
["Kirin's Winter Angel Coat","M"], 
["Long Swordsmanship School Uniform","M"],
["Magic School Uniform","F"],   
["Short Swordsmanship School Uniform","F"],
["Xiao-Lung Juen's Formal Suit","F"],   
["Blacksmith Manuals",""],  
["Cuirassier Helm",""],  
["Dagger",""],  
["Dustin Silver Knight Vambrace",""],  
["Fluted Short Sword",""],  
["Japanese Dagger",""],  
["Japanese One-handed Sword",""], 
["Japanese Twin Sword Sword",""],  
["Pickaxe",""], 
["Round Shield",""],  
["Weeding Hoe",""],  
["HP & Stamina 30 Potion","x5"], 
["Production Materials",""],  
["Common Fabric","x10"], 
["Common Finishing Thread","x10"],
["Common Leather","x10"], 
["Copper Ore","x10"], 
["Fine Finishing Thread","x10"],
["Fine Leather","x10"], 
["Fine Leather Strap","x10"], 
["Fine Fabric","x10"], 
["Finest Fabric","x5"], 
["Finest Finishing Thread","x5"],
["Finest Leather","x5"], 
["Finest Leather Strap","x5"],
["Fog Silk","x10"],  
["Fine Silk","x30"], 
["Gold Ingot","x10"], 
["Iron Ore","x10"], 
["Magical Silver Thread","x5"], 
["Magical Golden Thread","x5"],
["Magical Silver Thread","x10"], 
["Magical Golden Thread","x10"],  
["Mythril Ore","x5"], 
["Silver Ore","x10"],
["Thick Thread Ball","x5"], 
["Thin Thread Ball","x5"], 
["Miscellaneous",""],  
["Holy Water of Lymilark","x3"], 
["Wool Collection Pouch",""],  
["Cash Shop/Advanced Play Items",""],  
["Dye Ampoule",""], 
["Fixed Color Dye Ampoule",""],  
["Red Dye Ampoule",""], 
["Bastard Sword",""],  
["Bipennis",""],  
["Bone Marine Sword",""],  
["Crossbow",""],  
["Dragon Blade",""],  
["Gladius",""],  
["Hooked Cutlass",""],  
["Japanese One-handed Sword",""],  
["Longsword",""],  
["Mace",""],  
["Two-Handed Sword",""],  
["Blacksmith Hammer",""],  
["Cooking Knife",""],  
["Cooking Pot",""],  
["Cooking Table",""],  
["Fishing Rod",""],  
["Gathering Axe",""],  
["Gathering Knife",""],  
["Ladle",""],  
["Pickaxe",""],  
["Rolling Pin",""],  
["Sickle",""],  
["Weeding Hoe",""],  
["Weaving Gloves",""],  
["Common Silk Weaving Gloves",""],  
["Fine Fabric Weaving Gloves",""],  
["Fine Silk Weaving Gloves",""],  
["Finest Fabric Weaving Gloves",""],  
["Professional Silk Weaving Gloves",""],  
["Advanced Chef's Hat",""],  
["Apron Dress",""],  
["Apprentice Chef's Hat",""], 
["Arish Ashuvain Armor","F"],
["Arish Ashuvain Armor","M"], 
["Bear Robe",""],  
["Big Chain Full Helm",""],  
["Bone Marine Armor","F"],  
["Coco Rabbit Robe",""], 
["Cores' Cute Ribbon Shoes",""],  
["devCAT Brooch",""],  
["Dustin Silver Knight Armor",""],  
["Elegant Gothic Dress Long Type",""],  
["Elegant Gothic Dress Short Type",""],  
["Elegant Gothic Suit",""],  
["Ella's Vest Skirt",""],  
["European Comp",""],  
["Graceful Plate Armor",""],  
["Kirinusjin's Half-plate Armor","F"], 
["Long Swordsmanship School Uniform","M"], 
["Nathane Snow Mountain Coat",""],  
["One Piece Apron",""],  
["Ring",""], 
["Sasha Robe",""],  
["Short Swordsmanship School Uniform","F"],  
["Siren's Bat Wing Mask",""],  
["Siren's Cat Mask",""],  
["Siren's Glasses",""],  
["Siren's Mask",""],  
["Siren's Small Wing Mask",""],  
["Siren's Wing Mask",""],  
["Tioz Armor (F)","Light Pink"],
["Tork's Chef Uniform","F"], 
["Wing Half Helm",""],  
["Xiao-Lung Juen's Dress Shoes","F"],
["XL Pelican Protector",""],  
["Sewing Patterns",""],  
["Bone Marine Armor","M"], 
["Bone Marine Armor","F"],
["Cores' Healer Dress",""],  
["Cores' Healer Gloves",""],  
["Ella's Vest Skirt",""],  
["Kirin's Winter Angel Gloves",""],  
["Kirin's Winter Angel Cap",""],  
["Kirin's Winter Angel Coat","F"],  
["Kirin's Winter Angel Coat","M"], 
["Long Swordsmanship School Uniform","M"],
["Magic School Uniform","F"],   
["Short Swordsmanship School Uniform","F"],
["Xiao-Lung Juen's Formal Suit","F"],   
["Blacksmith Manuals",""],  
["Cuirassier Helm",""],  
["Dagger",""],  
["Dustin Silver Knight Vambrace",""],  
["Fluted Short Sword",""],  
["Japanese Dagger",""],  
["Japanese One-handed Sword",""], 
["Japanese Twin Sword Sword",""],  
["Pickaxe",""], 
["Round Shield",""],  
["Weeding Hoe",""],  
["HP & Stamina 30 Potion","x5"], 
["Production Materials",""],  
["Common Fabric","x10"], 
["Common Finishing Thread","x10"],
["Common Leather","x10"], 
["Copper Ore","x10"], 
["Fine Finishing Thread","x10"],
["Fine Leather","x10"], 
["Fine Leather Strap","x10"], 
["Fine Fabric","x10"], 
["Finest Fabric","x5"], 
["Finest Finishing Thread","x5"],
["Finest Leather","x5"], 
["Finest Leather Strap","x5"],
["Fog Silk","x10"],  
["Fine Silk","x30"], 
["Gold Ingot","x10"], 
["Iron Ore","x10"], 
["Magical Silver Thread","x5"], 
["Magical Golden Thread","x5"],
["Magical Silver Thread","x10"], 
["Magical Golden Thread","x10"],  
["Mythril Ore","x5"], 
["Silver Ore","x10"],
["Thick Thread Ball","x5"], 
["Thin Thread Ball","x5"], 
["Miscellaneous",""],  
["Holy Water of Lymilark","x3"], 
["Wool Collection Pouch",""],  
["Cash Shop/Advanced Play Items",""],  
["Dye Ampoule",""], 
["Fixed Color Dye Ampoule",""],  
["Red Dye Ampoule",""], 
["Mass Holy Water","x3"] 
];