Osla = [
["Japanese Dagger","*"],  
["Masamune","*"],  
["Muramasa","*"],  
["Ring Gloves","*"],  
["Swan Wing Cap","*"],  
["Yoshimitsu","*"],  
["Darkness Valencia's Cross Line Plate Armor","*"], 
["Raven Gladius","*"],  
["Pink Gladius","*"],   
["Bastard Sword",""],  
["Bipennis",""],  
["Claymore",""],  
["Combat Wand",""],  
["Composite Bow",""],  
["Crossbow",""],  
["Dagger",""],  
["Fire Wand",""],  
["Fluted Short Sword",""],  
["Gladius",""],  
["Healing Wand",""],  
["Hooked Cutlass",""],  
["Ice Wand",""],  
["Japanese One-handed Sword",""],  
["Leather Long Bow",""],  
["Longsword",""],  
["Lightning Wand",""],  
["Mace",""],  
["Short Sword",""],  
["Warhammer",""],  
["Shields",""],  
["Kite Shield",""],  
["Light Hetero Kite Shield",""],  
["Equipment",""],  
["Arish Ashuvain Armor","F"],  
["Arish Ashuvain Armor","M"],  
["Arish Ashuvain Boots","F"],  
["Arish Ashuvain Boots","M"],  
["Basnet",""],  
["Big Pelican Protector",""],  
["Big Panache Head Protector",""],  
["Bird Face Cap",""],  
["Blacksmith Shoes",""],  
["Bone Helm",""],  
["Bone Marine Armor",""],  
["Camelle Spirit Boots",""],  
["Cores' Thief Gloves",""],  
["Cross Full Helm",""],  
["Cuirassier Helm",""],  
["Dragon Crest",""],  
["Drandos Leather Mail","F"],  
["Dustin Silver Knight Armor",""],  
["European Comp",""],  
["Evil Dying Crown",""],  
["Field Combat Shoes",""],  
["Fluted Full Helm",""],  
["Fluted Gauntlet",""],  
["Greave Boots",""],  
["Guardian Helm",""],  
["Hunter Boots",""],  
["Iron Mask Headgear",""],  
["Kirinusjin's Half-plate Armor","F"],  
["Kirinusjin's Half-plate Armor","M"],  
["Leather Coat Shoes",""],  
["Leather Gloves",""],  
["Leather Shoes","Type 1"],  
["Leather Shoes","Type 5"],  
["Leminia's Holy Moon Armor","F"],  
["Leminia's Holy Moon Armor","M"],  
["Linen Cuirass (F)",""],  
["Linen Gloves",""],  
["Lorica Sandals",""], 
["Magic School Shoes",""],  
["Panache Head Protector",""],  
["Plate Boots",""],  
["Quilting Gloves",""],  
["Ring Mail Helm",""],  
["Round Polean Plate Boots",""],  
["Slit Full Helm",""],  
["Studded Bracelet",""],  
["Spiked Cap",""],  
["Swordsman Gloves",""],  
["Swordsman Shoes",""],  
["Swordswoman Gloves",""],  
["Swordswoman Shoes",""],  
["Thief Shoes",""],  
["Twin Horn Cap",""],  
["Ulna Protector Gloves",""],  
["Valencia's Cross Line Plate Armor","M"],  
["Waterdrop Cap",""],  
["Wing Half Helm",""], 
["Rank E - Fox Hunter's",""],  
["Rank C - Wolf Hunter's",""],  
["Rank B - Fox",""],  
["Rank 9 - Silver Fox",""],  
["Rank D - Kobold",""],  
["Rank B - Giant",""],  
["Rank 9 - Raven",""],  
["Rank 6 - Knight",""],  
["HP & Stamina 50 Potion","x3"],  
["HP 100 Potion","x3"],  
["MP 50 Potion","x5"],  
["Stamina 50 Potion","x5"],  
["Stamina 100 Potion","x3"],  
["Age Potion - 10-Year-Old - 30 Days",""], 
["Age Potion - 11-Year-Old - 30 Days",""], 
["Age Potion - 12-Year-Old - 30 Days",""], 
["Age Potion - 15-Year-Old - 30 Days",""], 
["Age Potion - 16-Year-Old - 30 Days",""], 
["Age Potion - 17-Year-Old - 30 Days",""], 
["Massive Holy Water of Lymilark","x3"],  
["Bastard Sword",""],  
["Bipennis",""],  
["Claymore",""],  
["Combat Wand",""],  
["Composite Bow",""],  
["Crossbow",""],  
["Dagger",""],  
["Fire Wand",""],  
["Fluted Short Sword",""],  
["Gladius",""],  
["Healing Wand",""],  
["Hooked Cutlass",""],  
["Ice Wand",""],  
["Japanese One-handed Sword",""],  
["Leather Long Bow",""],  
["Longsword",""],  
["Lightning Wand",""],  
["Mace",""],  
["Short Sword",""],  
["Warhammer",""],  
["Shields",""],  
["Kite Shield",""],  
["Light Hetero Kite Shield",""],  
["Equipment",""],  
["Arish Ashuvain Armor","F"],  
["Arish Ashuvain Armor","M"],  
["Arish Ashuvain Boots","F"],  
["Arish Ashuvain Boots","M"],  
["Basnet",""],  
["Big Pelican Protector",""],  
["Big Panache Head Protector",""],  
["Bird Face Cap",""],  
["Blacksmith Shoes",""],  
["Bone Helm",""],  
["Bone Marine Armor",""],  
["Camelle Spirit Boots",""],  
["Cores' Thief Gloves",""],  
["Cross Full Helm",""],  
["Cuirassier Helm",""],  
["Dragon Crest",""],  
["Drandos Leather Mail","F"],  
["Dustin Silver Knight Armor",""],  
["European Comp",""],  
["Evil Dying Crown",""],  
["Field Combat Shoes",""],  
["Fluted Full Helm",""],  
["Fluted Gauntlet",""],  
["Greave Boots",""],  
["Guardian Helm",""],  
["Hunter Boots",""],  
["Iron Mask Headgear",""],  
["Kirinusjin's Half-plate Armor","F"],  
["Kirinusjin's Half-plate Armor","M"],  
["Leather Coat Shoes",""],  
["Leather Gloves",""],  
["Leather Shoes","Type 1"],  
["Leather Shoes","Type 5"],  
["Leminia's Holy Moon Armor","F"],  
["Leminia's Holy Moon Armor","M"],  
["Linen Cuirass (F)",""],  
["Linen Gloves",""],  
["Lorica Sandals",""], 
["Magic School Shoes",""],  
["Panache Head Protector",""],  
["Plate Boots",""],  
["Quilting Gloves",""],  
["Ring Mail Helm",""],  
["Round Polean Plate Boots",""],  
["Slit Full Helm",""],  
["Studded Bracelet",""],  
["Spiked Cap",""],  
["Swordsman Gloves",""],  
["Swordsman Shoes",""],  
["Swordswoman Gloves",""],  
["Swordswoman Shoes",""],  
["Thief Shoes",""],  
["Twin Horn Cap",""],  
["Ulna Protector Gloves",""],  
["Valencia's Cross Line Plate Armor","M"],  
["Waterdrop Cap",""],  
["Wing Half Helm",""], 
["Rank E - Fox Hunter's",""],  
["Rank C - Wolf Hunter's",""],  
["Rank B - Fox",""],  
["Rank 9 - Silver Fox",""],  
["Rank D - Kobold",""],  
["Rank B - Giant",""],  
["Rank 9 - Raven",""],  
["Rank 6 - Knight",""],  
["HP & Stamina 50 Potion","x3"],  
["HP 100 Potion","x3"],  
["MP 50 Potion","x5"],  
["Stamina 50 Potion","x5"],  
["Stamina 100 Potion","x3"],  
["Age Potion - 10-Year-Old - 30 Days",""], 
["Age Potion - 11-Year-Old - 30 Days",""], 
["Age Potion - 12-Year-Old - 30 Days",""], 
["Age Potion - 15-Year-Old - 30 Days",""], 
["Age Potion - 16-Year-Old - 30 Days",""], 
["Age Potion - 17-Year-Old - 30 Days",""], 
["Massive Holy Water of Lymilark","x3"], 
["Bastard Sword",""],  
["Bipennis",""],  
["Claymore",""],  
["Combat Wand",""],  
["Composite Bow",""],  
["Crossbow",""],  
["Dagger",""],  
["Fire Wand",""],  
["Fluted Short Sword",""],  
["Gladius",""],  
["Healing Wand",""],  
["Hooked Cutlass",""],  
["Ice Wand",""],  
["Japanese One-handed Sword",""],  
["Leather Long Bow",""],  
["Longsword",""],  
["Lightning Wand",""],  
["Mace",""],  
["Short Sword",""],  
["Warhammer",""],  
["Shields",""],  
["Kite Shield",""],  
["Light Hetero Kite Shield",""],  
["Equipment",""],  
["Arish Ashuvain Armor","F"],  
["Arish Ashuvain Armor","M"],  
["Arish Ashuvain Boots","F"],  
["Arish Ashuvain Boots","M"],  
["Basnet",""],  
["Big Pelican Protector",""],  
["Big Panache Head Protector",""],  
["Bird Face Cap",""],  
["Blacksmith Shoes",""],  
["Bone Helm",""],  
["Bone Marine Armor",""],  
["Camelle Spirit Boots",""],  
["Cores' Thief Gloves",""],  
["Cross Full Helm",""],  
["Cuirassier Helm",""],  
["Dragon Crest",""],  
["Drandos Leather Mail","F"],  
["Dustin Silver Knight Armor",""],  
["European Comp",""],  
["Evil Dying Crown",""],  
["Field Combat Shoes",""],  
["Fluted Full Helm",""],  
["Fluted Gauntlet",""],  
["Greave Boots",""],  
["Guardian Helm",""],  
["Hunter Boots",""],  
["Iron Mask Headgear",""],  
["Kirinusjin's Half-plate Armor","F"],  
["Kirinusjin's Half-plate Armor","M"],  
["Leather Coat Shoes",""],  
["Leather Gloves",""],  
["Leather Shoes","Type 1"],  
["Leather Shoes","Type 5"],  
["Leminia's Holy Moon Armor","F"],  
["Leminia's Holy Moon Armor","M"],  
["Linen Cuirass (F)",""],  
["Linen Gloves",""],  
["Lorica Sandals",""], 
["Magic School Shoes",""],  
["Panache Head Protector",""],  
["Plate Boots",""],  
["Quilting Gloves",""],  
["Ring Mail Helm",""],  
["Round Polean Plate Boots",""],  
["Slit Full Helm",""],  
["Studded Bracelet",""],  
["Spiked Cap",""],  
["Swordsman Gloves",""],  
["Swordsman Shoes",""],  
["Swordswoman Gloves",""],  
["Swordswoman Shoes",""],  
["Thief Shoes",""],  
["Twin Horn Cap",""],  
["Ulna Protector Gloves",""],  
["Valencia's Cross Line Plate Armor","M"],  
["Waterdrop Cap",""],  
["Wing Half Helm",""], 
["Rank E - Fox Hunter's",""],  
["Rank C - Wolf Hunter's",""],  
["Rank B - Fox",""],  
["Rank 9 - Silver Fox",""],  
["Rank D - Kobold",""],  
["Rank B - Giant",""],  
["Rank 9 - Raven",""],  
["Rank 6 - Knight",""],  
["HP & Stamina 50 Potion","x3"],  
["HP 100 Potion","x3"],  
["MP 50 Potion","x5"],  
["Stamina 50 Potion","x5"],  
["Stamina 100 Potion","x3"],  
["Age Potion - 10-Year-Old - 30 Days",""], 
["Age Potion - 11-Year-Old - 30 Days",""], 
["Age Potion - 12-Year-Old - 30 Days",""], 
["Age Potion - 15-Year-Old - 30 Days",""], 
["Age Potion - 16-Year-Old - 30 Days",""], 
["Age Potion - 17-Year-Old - 30 Days",""], 
["Massive Holy Water of Lymilark","x3"], 
["Bastard Sword",""],  
["Bipennis",""],  
["Claymore",""],  
["Combat Wand",""],  
["Composite Bow",""],  
["Crossbow",""],  
["Dagger",""],  
["Fire Wand",""],  
["Fluted Short Sword",""],  
["Gladius",""],  
["Healing Wand",""],  
["Hooked Cutlass",""],  
["Ice Wand",""],  
["Japanese One-handed Sword",""],  
["Leather Long Bow",""],  
["Longsword",""],  
["Lightning Wand",""],  
["Mace",""],  
["Short Sword",""],  
["Warhammer",""],  
["Shields",""],  
["Kite Shield",""],  
["Light Hetero Kite Shield",""],  
["Equipment",""],  
["Arish Ashuvain Armor","F"],  
["Arish Ashuvain Armor","M"],  
["Arish Ashuvain Boots","F"],  
["Arish Ashuvain Boots","M"],  
["Basnet",""],  
["Big Pelican Protector",""],  
["Big Panache Head Protector",""],  
["Bird Face Cap",""],  
["Blacksmith Shoes",""],  
["Bone Helm",""],  
["Bone Marine Armor",""],  
["Camelle Spirit Boots",""],  
["Cores' Thief Gloves",""],  
["Cross Full Helm",""],  
["Cuirassier Helm",""],  
["Dragon Crest",""],  
["Drandos Leather Mail","F"],  
["Dustin Silver Knight Armor",""],  
["European Comp",""],  
["Evil Dying Crown",""],  
["Field Combat Shoes",""],  
["Fluted Full Helm",""],  
["Fluted Gauntlet",""],  
["Greave Boots",""],  
["Guardian Helm",""],  
["Hunter Boots",""],  
["Iron Mask Headgear",""],  
["Kirinusjin's Half-plate Armor","F"],  
["Kirinusjin's Half-plate Armor","M"],  
["Leather Coat Shoes",""],  
["Leather Gloves",""],  
["Leather Shoes","Type 1"],  
["Leather Shoes","Type 5"],  
["Leminia's Holy Moon Armor","F"],  
["Leminia's Holy Moon Armor","M"],  
["Linen Cuirass (F)",""],  
["Linen Gloves",""],  
["Lorica Sandals",""], 
["Magic School Shoes",""],  
["Panache Head Protector",""],  
["Plate Boots",""],  
["Quilting Gloves",""],  
["Ring Mail Helm",""],  
["Round Polean Plate Boots",""],  
["Slit Full Helm",""],  
["Studded Bracelet",""],  
["Spiked Cap",""],  
["Swordsman Gloves",""],  
["Swordsman Shoes",""],  
["Swordswoman Gloves",""],  
["Swordswoman Shoes",""],  
["Thief Shoes",""],  
["Twin Horn Cap",""],  
["Ulna Protector Gloves",""],  
["Valencia's Cross Line Plate Armor","M"],  
["Waterdrop Cap",""],  
["Wing Half Helm",""], 
["Rank E - Fox Hunter's",""],  
["Rank C - Wolf Hunter's",""],  
["Rank B - Fox",""],  
["Rank 9 - Silver Fox",""],  
["Rank D - Kobold",""],  
["Rank B - Giant",""],  
["Rank 9 - Raven",""],  
["Rank 6 - Knight",""],  
["HP & Stamina 50 Potion","x3"],  
["HP 100 Potion","x3"],  
["MP 50 Potion","x5"],  
["Stamina 50 Potion","x5"],  
["Stamina 100 Potion","x3"],  
["Age Potion - 10-Year-Old - 30 Days",""], 
["Age Potion - 11-Year-Old - 30 Days",""], 
["Age Potion - 12-Year-Old - 30 Days",""], 
["Age Potion - 15-Year-Old - 30 Days",""], 
["Age Potion - 16-Year-Old - 30 Days",""], 
["Age Potion - 17-Year-Old - 30 Days",""], 
["Massive Holy Water of Lymilark","x3"], 
["Bastard Sword",""],  
["Bipennis",""],  
["Claymore",""],  
["Combat Wand",""],  
["Composite Bow",""],  
["Crossbow",""],  
["Dagger",""],  
["Fire Wand",""],  
["Fluted Short Sword",""],  
["Gladius",""],  
["Healing Wand",""],  
["Hooked Cutlass",""],  
["Ice Wand",""],  
["Japanese One-handed Sword",""],  
["Leather Long Bow",""],  
["Longsword",""],  
["Lightning Wand",""],  
["Mace",""],  
["Short Sword",""],  
["Warhammer",""],  
["Shields",""],  
["Kite Shield",""],  
["Light Hetero Kite Shield",""],  
["Equipment",""],  
["Arish Ashuvain Armor","F"],  
["Arish Ashuvain Armor","M"],  
["Arish Ashuvain Boots","F"],  
["Arish Ashuvain Boots","M"],  
["Basnet",""],  
["Big Pelican Protector",""],  
["Big Panache Head Protector",""],  
["Bird Face Cap",""],  
["Blacksmith Shoes",""],  
["Bone Helm",""],  
["Bone Marine Armor",""],  
["Camelle Spirit Boots",""],  
["Cores' Thief Gloves",""],  
["Cross Full Helm",""],  
["Cuirassier Helm",""],  
["Dragon Crest",""],  
["Drandos Leather Mail","F"],  
["Dustin Silver Knight Armor",""],  
["European Comp",""],  
["Evil Dying Crown",""],  
["Field Combat Shoes",""],  
["Fluted Full Helm",""],  
["Fluted Gauntlet",""],  
["Greave Boots",""],  
["Guardian Helm",""],  
["Hunter Boots",""],  
["Iron Mask Headgear",""],  
["Kirinusjin's Half-plate Armor","F"],  
["Kirinusjin's Half-plate Armor","M"],  
["Leather Coat Shoes",""],  
["Leather Gloves",""],  
["Leather Shoes","Type 1"],  
["Leather Shoes","Type 5"],  
["Leminia's Holy Moon Armor","F"],  
["Leminia's Holy Moon Armor","M"],  
["Linen Cuirass (F)",""],  
["Linen Gloves",""],  
["Lorica Sandals",""], 
["Magic School Shoes",""],  
["Panache Head Protector",""],  
["Plate Boots",""],  
["Quilting Gloves",""],  
["Ring Mail Helm",""],  
["Round Polean Plate Boots",""],  
["Slit Full Helm",""],  
["Studded Bracelet",""],  
["Spiked Cap",""],  
["Swordsman Gloves",""],  
["Swordsman Shoes",""],  
["Swordswoman Gloves",""],  
["Swordswoman Shoes",""],  
["Thief Shoes",""],  
["Twin Horn Cap",""],  
["Ulna Protector Gloves",""],  
["Valencia's Cross Line Plate Armor","M"],  
["Waterdrop Cap",""],  
["Wing Half Helm",""], 
["Rank E - Fox Hunter's",""],  
["Rank C - Wolf Hunter's",""],  
["Rank B - Fox",""],  
["Rank 9 - Silver Fox",""],  
["Rank D - Kobold",""],  
["Rank B - Giant",""],  
["Rank 9 - Raven",""],  
["Rank 6 - Knight",""],  
["HP & Stamina 50 Potion","x3"],  
["HP 100 Potion","x3"],  
["MP 50 Potion","x5"],  
["Stamina 50 Potion","x5"],  
["Stamina 100 Potion","x3"],  
["Age Potion - 10-Year-Old - 30 Days",""], 
["Age Potion - 11-Year-Old - 30 Days",""], 
["Age Potion - 12-Year-Old - 30 Days",""], 
["Age Potion - 15-Year-Old - 30 Days",""], 
["Age Potion - 16-Year-Old - 30 Days",""], 
["Age Potion - 17-Year-Old - 30 Days",""], 
["Massive Holy Water of Lymilark","x3"], 
["axen Wing of Goddess - 7 Days",""]
];