Simon = [
["Fixed Color Dye Ampoule","Dark Blue"],
["Fixed Color Dye Ampoule","Gold"],
["Fixed Color Dye Ampoule","Hot Pink"],
["Fixed Color Dye Ampoule","Sky Blue"],
["Fixed Color Dye Ampoule","White"],
["Fixed Color Dye Ampoule","Neon Green"],
["Butler's Suit","*"],
["Fish Pin Kitty Hat","*"],
["Furry Bunny Headband 1-5","*"],
["Maid Dress - Short","*"], 
["Maid Long Dress","*"], 
["Maid's Headpiece","*"], 
["Muffler Robe","*"], 
["Pointy-eared Kitty Hat","*"], 
["Purple Rose Bouquet","*"], 
["Single Blue Rose","*"], 
["Single Purple Rose","*"], 
["Striped Kitty Hat","*"], 
["Wizard Suit for Men","Jackal"], 
["Wizard Suit for Men","Jackal"], 
["Wizard Suit for Women","Raccoon Cub"],
["Wizard Suit for Women","Raccoon Cub"],
["Blacksmith Shoes",""], 
["Blue Rose Bouquet",""], 
["Bolero Jumper Skirt",""], 
["Chinese Dress",""], 
["Cloth Shoes",""], 
["Coco Panda Robe",""], 
["Combat Shoes",""], 
["Cores' Boots","F"], 
["Cores' Cap",""], 
["Cores' Felt Hat",""], 
["Cores' Healer Dress",""], 
["Cores' Knit Cap",""], 
["Cores' Ninja Suit","F"], 
["Cores' Oriental Hat",""], 
["Criminal's Ski Mask",""], 
["Daisy Decoration",""], 
["Ella's Vest Skirt",""], 
["Ella's Strap Boots",""], 
["Enamel Shoes",""], 
["Feather Beret",""], 
["Female Business Suit",""], 
["Field Combat Shoes",""], 
["Goggle Cap",""], 
["Gothic Laced Skirt",""], 
["High Neck One-piece Dress",""], 
["Hunter Boots",""], 
["Jagged Mini Skirt",""], 
["Leather Boots",""], 
["Leather Coat Shoes",""], 
["Leather Shoes","Type 3"], 
["Leo Shoes",""], 
["Light Gloves",""], 
["Lirina's Shorts",""], 
["Lirina's Cap",""], 
["Lirina Striped Gloves",""], 
["Long Leather Gloves",""], 
["Lueys' Cleric Coat",""], 
["Magic School Uniform","F"],
["Magic School Uniform","M"], 
["Mario NY Modern Vintage Ensemble","M"], 
["Messenger Wear",""], 
["Mongo's Archer Cap",""], 
["Mongo Cap",""], 
["Mongo's Fashion Cap",""], 
["Mongo Jester Cap",""], 
["Mongo's Merchant Cap",""], 
["Mongo's Traveler Suit","F"], 
["Mongo's Wizard Hat",""], 
["Nathane Snow Mountain Coat",""], 
["Natural Vest Wear",""], 
["Oriental Warrior Suit",""], 
["Paper Hat",""], 
["Pinned Apron Skirt",""], 
["Popo Cap",""],
["Rose Bouquet",""], 
["Sandra's Sniper Suit Cap",""], 
["Sandra's Sniper Suit Boots","F"], 
["Sandra's Sniper Suit Boots","M"], 
["Selina School Uniform",""], 
["Sexy Lady Tanktop",""], 
["Short Swordsmanship School Uniform","F"],
["Stand Collar Sleeveless",""], 
["Starlight Robe",""], 
["Standard Gloves",""],
["Stripe Cap",""], 
["Terks' Tank Top and Shorts",""], 
["Terks' Two-Tone Tunic",""], 
["Thick Sandals",""], 
["Thicket Costume Kit",""], 
["Tight Tri-lined Glove",""], 
["Tiara",""], 
["Tork's Hunter Suit","F"], 
["Tork's Hunter Suit","M"],
["Track Suit Set",""], 
["Tricolor Robe",""], 
["Two-Tone Bizot Dress",""], 
["Vine-print Hunting Boots",""], 
["Wave-print Side-slit Tunic",""], 
["Wolf Robe",""], 
["Wood-rimmed Glasses",""], 
["Rank E - Fox Hunter's",""], 
["Rank E - Fox Hunter's",""], 
["Rank B - Fox",""], 
["Rank D - Kobold",""], 
["Rank 9 - Raven",""], 
["Red Potion",""], 
["Red Potion",""], 
["Diet Potion","F"],  
["Diet Potion","U"],
["Red Potion",""], 
["Black Youth Potion","x5"], 
["Miscellaneous",""], 
["Bald Wig",""], 
["Nao Costume Kit",""], 
["Sun Costume Kit",""], 
["Rock Costume Kit",""], 
["Tree Costume Kit",""], 
["Age Potion - 10-Year-Old",""], 
["Age Potion - 11-Year-Old",""], 
["Age Potion - 12-Year-Old",""], 
["Age Potion - 13-Year-Old",""], 
["Age Potion - 14-Year-Old",""], 
["Age Potion - 15-Year-Old",""], 
["Age Potion - 16-Year-Old",""], 
["Age Potion - 17 Year-Old",""], 
["Black Dye Ampoule",""], 
["Dye Ampoule","never expires"], 
["Full Recovery Potion","x3"],  
["Massive Holy Water of Lymilark","x3"], 
["Blacksmith Shoes",""], 
["Blue Rose Bouquet",""], 
["Bolero Jumper Skirt",""], 
["Chinese Dress",""], 
["Cloth Shoes",""], 
["Coco Panda Robe",""], 
["Combat Shoes",""], 
["Cores' Boots","F"], 
["Cores' Cap",""], 
["Cores' Felt Hat",""], 
["Cores' Healer Dress",""], 
["Cores' Knit Cap",""], 
["Cores' Ninja Suit","F"], 
["Cores' Oriental Hat",""], 
["Criminal's Ski Mask",""], 
["Daisy Decoration",""], 
["Ella's Vest Skirt",""], 
["Ella's Strap Boots",""], 
["Enamel Shoes",""], 
["Feather Beret",""], 
["Female Business Suit",""], 
["Field Combat Shoes",""], 
["Goggle Cap",""], 
["Gothic Laced Skirt",""], 
["High Neck One-piece Dress",""], 
["Hunter Boots",""], 
["Jagged Mini Skirt",""], 
["Leather Boots",""], 
["Leather Coat Shoes",""], 
["Leather Shoes","Type 3"], 
["Leo Shoes",""], 
["Light Gloves",""], 
["Lirina's Shorts",""], 
["Lirina's Cap",""], 
["Lirina Striped Gloves",""], 
["Long Leather Gloves",""], 
["Lueys' Cleric Coat",""], 
["Magic School Uniform","F"],
["Magic School Uniform","M"], 
["Mario NY Modern Vintage Ensemble","M"], 
["Messenger Wear",""], 
["Mongo's Archer Cap",""], 
["Mongo Cap",""], 
["Mongo's Fashion Cap",""], 
["Mongo Jester Cap",""], 
["Mongo's Merchant Cap",""], 
["Mongo's Traveler Suit","F"], 
["Mongo's Wizard Hat",""], 
["Nathane Snow Mountain Coat",""], 
["Natural Vest Wear",""], 
["Oriental Warrior Suit",""], 
["Paper Hat",""], 
["Pinned Apron Skirt",""], 
["Popo Cap",""],
["Rose Bouquet",""], 
["Sandra's Sniper Suit Cap",""], 
["Sandra's Sniper Suit Boots","F"], 
["Sandra's Sniper Suit Boots","M"], 
["Selina School Uniform",""], 
["Sexy Lady Tanktop",""], 
["Short Swordsmanship School Uniform","F"],
["Stand Collar Sleeveless",""], 
["Starlight Robe",""], 
["Standard Gloves",""],
["Stripe Cap",""], 
["Terks' Tank Top and Shorts",""], 
["Terks' Two-Tone Tunic",""], 
["Thick Sandals",""], 
["Thicket Costume Kit",""], 
["Tight Tri-lined Glove",""], 
["Tiara",""], 
["Tork's Hunter Suit","F"], 
["Tork's Hunter Suit","M"],
["Track Suit Set",""], 
["Tricolor Robe",""], 
["Two-Tone Bizot Dress",""], 
["Vine-print Hunting Boots",""], 
["Wave-print Side-slit Tunic",""], 
["Wolf Robe",""], 
["Wood-rimmed Glasses",""], 
["Rank E - Fox Hunter's",""], 
["Rank E - Fox Hunter's",""], 
["Rank B - Fox",""], 
["Rank D - Kobold",""], 
["Rank 9 - Raven",""], 
["Red Potion",""], 
["Red Potion",""], 
["Diet Potion","F"],  
["Diet Potion","U"],
["Red Potion",""], 
["Black Youth Potion","x5"], 
["Miscellaneous",""], 
["Bald Wig",""], 
["Nao Costume Kit",""], 
["Sun Costume Kit",""], 
["Rock Costume Kit",""], 
["Tree Costume Kit",""], 
["Age Potion - 10-Year-Old",""], 
["Age Potion - 11-Year-Old",""], 
["Age Potion - 12-Year-Old",""], 
["Age Potion - 13-Year-Old",""], 
["Age Potion - 14-Year-Old",""], 
["Age Potion - 15-Year-Old",""], 
["Age Potion - 16-Year-Old",""], 
["Age Potion - 17 Year-Old",""], 
["Black Dye Ampoule",""], 
["Dye Ampoule","never expires"], 
["Full Recovery Potion","x3"],  
["Massive Holy Water of Lymilark","x3"], 
["Blacksmith Shoes",""], 
["Blue Rose Bouquet",""], 
["Bolero Jumper Skirt",""], 
["Chinese Dress",""], 
["Cloth Shoes",""], 
["Coco Panda Robe",""], 
["Combat Shoes",""], 
["Cores' Boots","F"], 
["Cores' Cap",""], 
["Cores' Felt Hat",""], 
["Cores' Healer Dress",""], 
["Cores' Knit Cap",""], 
["Cores' Ninja Suit","F"], 
["Cores' Oriental Hat",""], 
["Criminal's Ski Mask",""], 
["Daisy Decoration",""], 
["Ella's Vest Skirt",""], 
["Ella's Strap Boots",""], 
["Enamel Shoes",""], 
["Feather Beret",""], 
["Female Business Suit",""], 
["Field Combat Shoes",""], 
["Goggle Cap",""], 
["Gothic Laced Skirt",""], 
["High Neck One-piece Dress",""], 
["Hunter Boots",""], 
["Jagged Mini Skirt",""], 
["Leather Boots",""], 
["Leather Coat Shoes",""], 
["Leather Shoes","Type 3"], 
["Leo Shoes",""], 
["Light Gloves",""], 
["Lirina's Shorts",""], 
["Lirina's Cap",""], 
["Lirina Striped Gloves",""], 
["Long Leather Gloves",""], 
["Lueys' Cleric Coat",""], 
["Magic School Uniform","F"],
["Magic School Uniform","M"], 
["Mario NY Modern Vintage Ensemble","M"], 
["Messenger Wear",""], 
["Mongo's Archer Cap",""], 
["Mongo Cap",""], 
["Mongo's Fashion Cap",""], 
["Mongo Jester Cap",""], 
["Mongo's Merchant Cap",""], 
["Mongo's Traveler Suit","F"], 
["Mongo's Wizard Hat",""], 
["Nathane Snow Mountain Coat",""], 
["Natural Vest Wear",""], 
["Oriental Warrior Suit",""], 
["Paper Hat",""], 
["Pinned Apron Skirt",""], 
["Popo Cap",""],
["Rose Bouquet",""], 
["Sandra's Sniper Suit Cap",""], 
["Sandra's Sniper Suit Boots","F"], 
["Sandra's Sniper Suit Boots","M"], 
["Selina School Uniform",""], 
["Sexy Lady Tanktop",""], 
["Short Swordsmanship School Uniform","F"],
["Stand Collar Sleeveless",""], 
["Starlight Robe",""], 
["Standard Gloves",""],
["Stripe Cap",""], 
["Terks' Tank Top and Shorts",""], 
["Terks' Two-Tone Tunic",""], 
["Thick Sandals",""], 
["Thicket Costume Kit",""], 
["Tight Tri-lined Glove",""], 
["Tiara",""], 
["Tork's Hunter Suit","F"], 
["Tork's Hunter Suit","M"],
["Track Suit Set",""], 
["Tricolor Robe",""], 
["Two-Tone Bizot Dress",""], 
["Vine-print Hunting Boots",""], 
["Wave-print Side-slit Tunic",""], 
["Wolf Robe",""], 
["Wood-rimmed Glasses",""], 
["Rank E - Fox Hunter's",""], 
["Rank E - Fox Hunter's",""], 
["Rank B - Fox",""], 
["Rank D - Kobold",""], 
["Rank 9 - Raven",""], 
["Red Potion",""], 
["Red Potion",""], 
["Diet Potion","F"],  
["Diet Potion","U"],
["Red Potion",""], 
["Black Youth Potion","x5"], 
["Miscellaneous",""], 
["Bald Wig",""], 
["Nao Costume Kit",""], 
["Sun Costume Kit",""], 
["Rock Costume Kit",""], 
["Tree Costume Kit",""], 
["Age Potion - 10-Year-Old",""], 
["Age Potion - 11-Year-Old",""], 
["Age Potion - 12-Year-Old",""], 
["Age Potion - 13-Year-Old",""], 
["Age Potion - 14-Year-Old",""], 
["Age Potion - 15-Year-Old",""], 
["Age Potion - 16-Year-Old",""], 
["Age Potion - 17 Year-Old",""], 
["Black Dye Ampoule",""], 
["Dye Ampoule","never expires"], 
["Full Recovery Potion","x3"],  
["Massive Holy Water of Lymilark","x3"], 
["Blacksmith Shoes",""], 
["Blue Rose Bouquet",""], 
["Bolero Jumper Skirt",""], 
["Chinese Dress",""], 
["Cloth Shoes",""], 
["Coco Panda Robe",""], 
["Combat Shoes",""], 
["Cores' Boots","F"], 
["Cores' Cap",""], 
["Cores' Felt Hat",""], 
["Cores' Healer Dress",""], 
["Cores' Knit Cap",""], 
["Cores' Ninja Suit","F"], 
["Cores' Oriental Hat",""], 
["Criminal's Ski Mask",""], 
["Daisy Decoration",""], 
["Ella's Vest Skirt",""], 
["Ella's Strap Boots",""], 
["Enamel Shoes",""], 
["Feather Beret",""], 
["Female Business Suit",""], 
["Field Combat Shoes",""], 
["Goggle Cap",""], 
["Gothic Laced Skirt",""], 
["High Neck One-piece Dress",""], 
["Hunter Boots",""], 
["Jagged Mini Skirt",""], 
["Leather Boots",""], 
["Leather Coat Shoes",""], 
["Leather Shoes","Type 3"], 
["Leo Shoes",""], 
["Light Gloves",""], 
["Lirina's Shorts",""], 
["Lirina's Cap",""], 
["Lirina Striped Gloves",""], 
["Long Leather Gloves",""], 
["Lueys' Cleric Coat",""], 
["Magic School Uniform","F"],
["Magic School Uniform","M"], 
["Mario NY Modern Vintage Ensemble","M"], 
["Messenger Wear",""], 
["Mongo's Archer Cap",""], 
["Mongo Cap",""], 
["Mongo's Fashion Cap",""], 
["Mongo Jester Cap",""], 
["Mongo's Merchant Cap",""], 
["Mongo's Traveler Suit","F"], 
["Mongo's Wizard Hat",""], 
["Nathane Snow Mountain Coat",""], 
["Natural Vest Wear",""], 
["Oriental Warrior Suit",""], 
["Paper Hat",""], 
["Pinned Apron Skirt",""], 
["Popo Cap",""],
["Rose Bouquet",""], 
["Sandra's Sniper Suit Cap",""], 
["Sandra's Sniper Suit Boots","F"], 
["Sandra's Sniper Suit Boots","M"], 
["Selina School Uniform",""], 
["Sexy Lady Tanktop",""], 
["Short Swordsmanship School Uniform","F"],
["Stand Collar Sleeveless",""], 
["Starlight Robe",""], 
["Standard Gloves",""],
["Stripe Cap",""], 
["Terks' Tank Top and Shorts",""], 
["Terks' Two-Tone Tunic",""], 
["Thick Sandals",""], 
["Thicket Costume Kit",""], 
["Tight Tri-lined Glove",""], 
["Tiara",""], 
["Tork's Hunter Suit","F"], 
["Tork's Hunter Suit","M"],
["Track Suit Set",""], 
["Tricolor Robe",""], 
["Two-Tone Bizot Dress",""], 
["Vine-print Hunting Boots",""], 
["Wave-print Side-slit Tunic",""], 
["Wolf Robe",""], 
["Wood-rimmed Glasses",""], 
["Rank E - Fox Hunter's",""], 
["Rank E - Fox Hunter's",""], 
["Rank B - Fox",""], 
["Rank D - Kobold",""], 
["Rank 9 - Raven",""], 
["Red Potion",""], 
["Red Potion",""], 
["Diet Potion","F"],  
["Diet Potion","U"],
["Red Potion",""], 
["Black Youth Potion","x5"], 
["Miscellaneous",""], 
["Bald Wig",""], 
["Nao Costume Kit",""], 
["Sun Costume Kit",""], 
["Rock Costume Kit",""], 
["Tree Costume Kit",""], 
["Age Potion - 10-Year-Old",""], 
["Age Potion - 11-Year-Old",""], 
["Age Potion - 12-Year-Old",""], 
["Age Potion - 13-Year-Old",""], 
["Age Potion - 14-Year-Old",""], 
["Age Potion - 15-Year-Old",""], 
["Age Potion - 16-Year-Old",""], 
["Age Potion - 17 Year-Old",""], 
["Black Dye Ampoule",""], 
["Dye Ampoule","never expires"], 
["Full Recovery Potion","x3"],  
["Massive Holy Water of Lymilark","x3"], 
["Red Dye Ampoule",""]
];